### ISSUE TITLE
Error: No default engine was specified and no extension was provided

### ISSUE THREAD

**Issue by Ganesh-Nexg** [didinj/mern-stack-crud#4]
Hi !
I installed this app, after running it is showing the following error
Error: No default engine was specified and no extension was provided.
    at new View (D:\xampp\htdocs\mp\5\node_modules\express\lib\view.js:61:11)
    at Function.render (D:\xampp\htdocs\mp\5\node_modules\express\lib\application.js:570:12)
    at ServerResponse.render (D:\xampp\htdocs\mp\5\node_modules\express\lib\response.js:1008:7)
    at D:\xampp\htdocs\mp\5\app.js:37:7
    at Layer.handle_error (D:\xampp\htdocs\mp\5\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (D:\xampp\htdocs\mp\5\node_modules\express\lib\router\index.js:315:13)
    at D:\xampp\htdocs\mp\5\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\xampp\htdocs\mp\5\node_modules\express\lib\router\index.js:335:12)
    at next (D:\xampp\htdocs\mp\5\node_modules\express\lib\router\index.js:275:10)
    at D:\xampp\htdocs\mp\5\app.js:26:3
    at Layer.handle [as handle_request] (D:\xampp\htdocs\mp\5\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\xampp\htdocs\mp\5\node_modules\express\lib\router\index.js:317:13)
    at D:\xampp\htdocs\mp\5\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\xampp\htdocs\mp\5\node_modules\express\lib\router\index.js:335:12)
    at next (D:\xampp\htdocs\mp\5\node_modules\express\lib\router\index.js:275:10)
    at SendStream.error (D:\xampp\htdocs\mp\5\node_modules\serve-static\index.js:121:7)
    at emitOne (events.js:116:13)
    at SendStream.emit (events.js:211:7)
    at SendStream.error (D:\xampp\htdocs\mp\5\node_modules\send\index.js:270:17)
    at SendStream.onStatError (D:\xampp\htdocs\mp\5\node_modules\send\index.js:421:12)
    at next (D:\xampp\htdocs\mp\5\node_modules\send\index.js:764:28)
    at D:\xampp\htdocs\mp\5\node_modules\send\index.js:772:23

Please solve this issue
Thanks in advance....

**Comment by didinj** [comment]
Fixed
